//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CATCUSTINFO.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_Info_Cus> TB_Info_Cus { get; set; }
        public virtual DbSet<TB_PackageNet> TB_PackageNet { get; set; }
        public virtual DbSet<TB_RegionCAT> TB_RegionCAT { get; set; }
        public virtual DbSet<TB_ServiceNet> TB_ServiceNet { get; set; }
        public virtual DbSet<TB_SpeedNet> TB_SpeedNet { get; set; }
    }
}
