//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CATCUSTINFO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PackageNet
    {
        public int PackNet_ID { get; set; }
        public string PackNet_Name { get; set; }
        public string PackNet_Detail { get; set; }
        public Nullable<int> SerNet_ID { get; set; }
    }
}
