//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CATCUSTINFO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_RegionCAT
    {
        public int RegCAT_ID { get; set; }
        public string RegCAT_Name { get; set; }
    }
}
