//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CATCUSTINFO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_SpeedNet
    {
        public int SpeedNet_ID { get; set; }
        public string SpeedNet_Name { get; set; }
        public Nullable<int> SpeedNet_Down { get; set; }
        public Nullable<int> SpeedNet_Up { get; set; }
        public string SpeedNet_Detail { get; set; }
        public Nullable<int> PackNet_ID { get; set; }
    }
}
